const STORAGE='ishami_v2_data';
const defaultImg='assets/ishami-property.jpg';
const defaults={apartments:[
{id:'luxury',title:'Luxury One Bedroom',price:85000,bedrooms:1,maxGuests:2,description:'Elegant furnished apartment with modern kitchen, Wi-Fi and comfortable living space.',image:defaultImg},
{id:'executive',title:'Executive Two Bedroom',price:140000,bedrooms:2,maxGuests:4,description:'Spacious premium apartment for families, business travelers and extended stays.',image:defaultImg},
{id:'family',title:'Family Residence',price:180000,bedrooms:3,maxGuests:6,description:'A large residence with generous living areas, full kitchen and secure parking.',image:defaultImg}],gallery:[defaultImg,defaultImg,defaultImg],bookings:[]};
let data=JSON.parse(localStorage.getItem(STORAGE)||'null')||structuredClone(defaults);let selectedTotal=0;
const save=()=>localStorage.setItem(STORAGE,JSON.stringify(data));
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(){const grid=document.querySelector('#roomGrid'),sel=document.querySelector('#roomSelect'),gallery=document.querySelector('#galleryGrid');grid.innerHTML=data.apartments.map((a,i)=>`<article class="room-card"><div class="room-image"><img src="${a.image}" alt="${esc(a.title)}"><span class="room-badge">${i===0?'POPULAR':'AVAILABLE'}</span></div><div class="room-body"><div class="room-top"><h3>${esc(a.title)}</h3><span>★★★★★</span></div><p>${esc(a.description)}</p><ul class="room-features"><li>${a.bedrooms} bedroom${a.bedrooms>1?'s':''}</li><li>Up to ${a.maxGuests} guests</li><li>Wi-Fi</li><li>Kitchen</li></ul><div class="room-bottom"><strong>${a.price.toLocaleString()} RWF / night</strong><a href="#booking" onclick="selectRoom('${a.id}')">Reserve →</a></div></div></article>`).join('');sel.innerHTML='<option value="">Choose an apartment</option>'+data.apartments.map(a=>`<option value="${a.id}">${esc(a.title)} — ${a.price.toLocaleString()} RWF/night</option>`).join('');gallery.innerHTML=data.gallery.map((p,i)=>`<figure class="${i===0?'gallery-main':''}"><img src="${p}" alt="Ishami Legacy Apartments gallery"></figure>`).join('');renderAdmin();}
window.selectRoom=id=>{document.querySelector('#roomSelect').value=id;updatePrice()};
const form=document.querySelector('#bookingForm'),checkin=form.elements.checkin,checkout=form.elements.checkout;const iso=new Date().toISOString().slice(0,10);checkin.min=checkout.min=iso;checkin.onchange=()=>{checkout.min=checkin.value||iso;updatePrice()};checkout.onchange=updatePrice;document.querySelector('#roomSelect').onchange=updatePrice;
function updatePrice(){const a=data.apartments.find(x=>x.id===document.querySelector('#roomSelect').value);const box=document.querySelector('#priceBox');if(!a||!checkin.value||!checkout.value){box.textContent='Select an apartment and dates to see your estimated total.';selectedTotal=0;return}const nights=Math.ceil((new Date(checkout.value)-new Date(checkin.value))/86400000);if(nights<=0){box.textContent='Check-out must be after check-in.';selectedTotal=0;return}selectedTotal=nights*a.price;box.innerHTML=`<b>${nights} night${nights>1?'s':''}</b> × ${a.price.toLocaleString()} RWF = <strong>${selectedTotal.toLocaleString()} RWF</strong>`}
form.onsubmit=e=>{e.preventDefault();if(!selectedTotal){updatePrice();return alert('Please choose valid dates and an apartment.')}const fd=new FormData(form),a=data.apartments.find(x=>x.id===fd.get('room'));const photo=fd.get('guestPhoto');const booking={id:'BK-'+Date.now(),name:fd.get('name'),email:fd.get('email'),phone:fd.get('phone'),room:a.title,guests:fd.get('guests'),checkin:fd.get('checkin'),checkout:fd.get('checkout'),message:fd.get('message'),total:selectedTotal,status:'Pending',created:new Date().toLocaleString()};const finish=()=>{data.bookings.unshift(booking);save();render();const msg=`Hello Ishami Legacy Apartments,%0A%0ABooking ID: ${booking.id}%0AGuest: ${booking.name}%0AApartment: ${booking.room}%0ADates: ${booking.checkin} to ${booking.checkout}%0AGuests: ${booking.guests}%0AEstimated total: ${booking.total.toLocaleString()} RWF%0A%0APlease confirm my booking.`;window.open('https://wa.me/250782204940?text='+msg,'_blank');alert('Booking request created successfully! Your booking ID is '+booking.id);form.reset();document.querySelector('#priceBox').textContent='Select an apartment and dates to see your estimated total.'};if(photo&&photo.size){if(photo.size>2*1024*1024)return alert('Please use a photo smaller than 2 MB for this browser demo.');const r=new FileReader();r.onload=()=>{booking.guestPhoto=r.result;finish()};r.readAsDataURL(photo)}else finish()};
const modal=document.querySelector('#adminModal');document.querySelector('#adminOpen').onclick=()=>modal.classList.remove('hidden');document.querySelector('[data-close]').onclick=()=>modal.classList.add('hidden');document.querySelector('#adminLoginBtn').onclick=()=>{if(document.querySelector('#adminPassword').value==='ishami2026'){document.querySelector('#adminLogin').classList.add('hidden');document.querySelector('#dashboard').classList.remove('hidden');renderAdmin()}else alert('Incorrect password')};document.querySelector('#adminLogout').onclick=()=>{document.querySelector('#dashboard').classList.add('hidden');document.querySelector('#adminLogin').classList.remove('hidden');document.querySelector('#adminPassword').value=''};
document.querySelectorAll('.dash-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.dash-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab-content').forEach(x=>x.classList.add('hidden'));document.querySelector('#tab-'+b.dataset.tab).classList.remove('hidden')});
function renderAdmin(){const bl=document.querySelector('#bookingList');if(!bl)return;bl.innerHTML=data.bookings.length?data.bookings.map(b=>`<div class="booking-item"><div>${b.guestPhoto?`<img src="${b.guestPhoto}" class="guest-thumb">`:''}<b>${esc(b.name)}</b><span>${esc(b.id)} • ${esc(b.room)}</span><span>${esc(b.checkin)} → ${esc(b.checkout)} • ${Number(b.total).toLocaleString()} RWF</span><span class="status ${b.status.toLowerCase()}">${b.status}</span></div><div><button onclick="setStatus('${b.id}','Confirmed')">Confirm</button><button onclick="setStatus('${b.id}','Cancelled')">Cancel</button><button onclick="deleteBooking('${b.id}')">Delete</button></div></div>`).join(''):'<p class="muted">No bookings yet.</p>';const al=document.querySelector('#adminApartmentList');al.innerHTML=data.apartments.map(a=>`<div class="admin-row"><span><b>${esc(a.title)}</b> — ${a.price.toLocaleString()} RWF/night</span><button onclick="deleteApartment('${a.id}')">Delete</button></div>`).join('');const gl=document.querySelector('#adminGalleryList');gl.innerHTML=data.gallery.map((p,i)=>`<div><img src="${p}"><button onclick="deletePhoto(${i})">Delete</button></div>`).join('')}
window.setStatus=(id,status)=>{const b=data.bookings.find(x=>x.id===id);b.status=status;save();renderAdmin()};window.deleteBooking=id=>{data.bookings=data.bookings.filter(x=>x.id!==id);save();renderAdmin()};window.deleteApartment=id=>{data.apartments=data.apartments.filter(x=>x.id!==id);save();render()};window.deletePhoto=i=>{data.gallery.splice(i,1);save();render()};
function fileData(file,cb){if(!file)return cb(defaultImg);if(file.size>2*1024*1024)return alert('Image must be smaller than 2 MB for browser storage demo.');const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
document.querySelector('#apartmentForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);fileData(f.get('image'),image=>{data.apartments.push({id:'apt-'+Date.now(),title:f.get('title'),price:Number(f.get('price')),bedrooms:Number(f.get('bedrooms')),maxGuests:Number(f.get('maxGuests')),description:f.get('description'),image});save();e.target.reset();render()})};document.querySelector('#photoForm').onsubmit=e=>{e.preventDefault();const file=new FormData(e.target).get('photo');fileData(file,p=>{data.gallery.push(p);save();e.target.reset();render()})};document.querySelector('#year').textContent=new Date().getFullYear();render();
